"""empty message

Revision ID: 3bc220571ae4
Revises: 
Create Date: 2023-05-26 09:03:26.172074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc220571ae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('street_number',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('region')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=80), nullable=False))
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('street_number',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
